### ISSUE TITLE
Company and Branch Selection

### ISSUE THREAD

**Issue by johnenrick** [johnenrick/godigit#97]
**Scenario**  
After the user logged in, the user will then select which company and/or branch if they have multiple company and/or branch

**Flow**
1. The user logged in successfully
2. The system will then check if it the user has multiple company. If it has go to _step 3_, else go to _step 4_
3. Ask the user which company to use 
4. The system will then check if it the user has multiple branch in the selected company. If it has go to _step 5_, else go to _step 6_
5. Ask the user which branch to use
6. Set save company and branch to cookies

**Task**  
- [ ] Create a page for selecting company and branch
- [ ] Redirect the user after logged in to company and branch selection page if it has multiple company/branch
- [ ] Set the cookies using the function _setCompany_ in service/auth
